apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-repo-username-token
  namespace: jenkins
spec:
  encryptedData:
    password: AgATckCtv6EHhI/vaagN01IxCdgyHK9dMXoqsYb5auuaw6KSIkLju17Ih2Mq2QrPzfXCmFFqZbLDyLs701Oy4SHi3qpE5DyopyGXiXoDLtxkIzpXjSp/l7+cud3QDKJkw7Ei6ipq6gRO7QQmTRad7QdB4DZ1WbPcnD+mggWlvCpOa+20JC++kTOMj4RKsNiLe497JA7auaA/aGM8LR4uTnSvzmF80VL42ff+OxLF9LS9BvkJQGSa7kMLJK8MLkzfhVahMMS4GalbRs+bziUIAl5JxvpopiVLwcpjS+9cfV+SHAABfbn/9rn2/VNpQchgVBP4Fe1loKc4J0mLEe4P7yM36dfW8Nanqes30NCqw/QMLtNM7BY7wujENR7Rc9UisYTjvGZ2EcgGq8ebWUX4pvzI6GvK6mnuUlbI3+sHJaxSLIFydJmomOw/ndWD3/5A9kN6t7Eits0yqa6DhX9mhMsHkmmLuz8G/dFtdSOq8BGkgqmUZwNT+0Qghc1j8FiXH55cJNpaMtOUV4hhf66OdSMVhdWudVcD9uGm4qs6Om6Pqine0Js2AfPAJCD6nOZpTeVQQQAs7fqNhhkxtnvIfwF5tcjrsxncQzUFI+34XZtrgBo5dXAQKsE/jh/kHoVAcflsrn9Owi6a78RD5bJhR9RdS0F3dy3POxZeghMC1EENobV8PTXSMsQUjnC0YT6X0A3s0c47c4XumQYFqpyHuTUeDY3PWK6tSkDJdWqsb4B5Esum4f7sLLjP
    username: AgAjLkrC/onfQ3ha1OBEugz+iwsDm6bTy7b9PZRRpqvuywlAgriTlVSO3c+xPwlr6AzRR8FD5Pv9RrzMiWDFiAR5xBcnlXKDCkK/cUS6T72Ya4a2Fb30v4+wr5e/ML4WtMZfFHrvDMvWsUJr85HbxXF+pG2qFNC2YypBCNvgTRwBOC7xhj4OZPhaKUrcMaSAoKldwvzfN/z7OR6rLsmHCqttbY9etP2T5RLJQseVpf3/Zqn5dkcRTNwgtw7OX3/dMW24HAOq4w0SiXG+UBb3xhTEWQV8YgaEofEHoNJFNLtfYV8IRx23mDgPFaKqNTHsrLP+KVT5AAlQxXCo3YO6y1KxqbIy2bvLjoqdB1wSCB51VZZkQ5SWqqNLuSEC9QULC4CG13l6XWF9pBOGaAZoorVsRXwzbNDsljIX4PQs0m0w0g2MeC83JsCFPwiZI7n4XmSUrckdarxh95dBnndTpd0P1bSjauxtd7ZnJDnl/7jZutmGPKmNyrbvW3idh5fpqSnRyvdN8x9ajhtGSZeD6d/uYkU+3gHge0SQwDsC6n7SZ7fo130yBTU/EdcN8NFTBSstuFbocS3tdYeKOMijczOb0RoSkPxhO6Bl5CvyohpcEGGXtFwZNWnMztRsYAhFawvH1/rtW4Z7MEq4/02VPHwJ7aYrYEYHHQSkaFRuKj6VjbCbnMGrn9jNra1/GfxBUotzYjcMIeM=
  template:
    metadata:
      annotations:
        jenkins.io/credentials-description: Github Exital Username Repo Token
      creationTimestamp: null
      labels:
        jenkins.io/credentials-type: usernamePassword
      name: github-repo-username-token
      namespace: jenkins
    type: Opaque

