apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-portfolio-ci
  namespace: jenkins
spec:
  encryptedData:
    text: AgAa7x1uFtfo9pA/wqcB7vWk74m3rQy16LzzTldTZsUu0AtfxBg/3/+3H+S4sZCuZPjKn0634Y0BkpXUSHUPJLpXewRPqzGxwNAyHMbN4PwzMeydOmyji0Op0kPbF5sRNbh5TsZRDalIEsjRIsmqsfRLnCxKRcADh5QI8Ecz6E+TjY6BCX7zyiLQKv9LnFmey4Gu8Izg+pwE2Em7DmI8As0mMY5+9RuqS7e9nMUiG2JlqJzOLn+gRdo5icccDRLGW+HV6GCb7fmyOljpdNC4P9GXpmpUSHQbH+AHj4f5ty5eb8Pj4zNuuZ7ShCX5YwujlIc+N4UJbPfDEk5T2oC5pfmV9x0i1ynQRKGYc7KwErj85lv18c3astxqCOXk6QDDuAIpPnBj1S5htBNCIUMWHLe1QpDqQK5I0MJ4psxSws4Cv7VwZB0a1KMbtJWC8/F0fYif3lceW2dq8NmljcgWYCeMzGc8UiMQvyUL/BVMdCZwiFwsS5bGfJSZFYemEGSFHCRqlepD2aSRaR9IfhVo9s2H5zv66EMjjD1TCxuhpTQxpPCbDH/i/32Vzil2O1I+1ulstP0sjkKsUl2ZOJm88Q9ufZ5lXo+ggOaTaeYgAkiDuClNXjJBG82rhqPbcI3GuHvJVxkUEqOY2cmbjVrx8dLGOV354QuCp6p23A+d5mSP9H0iDASynYiWLmkYYPbGuACeBE3yFCdQjla9MR8nkglpgKmTZxDniQ==
  template:
    metadata:
      annotations:
        jenkins.io/credentials-description: Github WebHook token for Portfolio-CI
          pipeline
      creationTimestamp: null
      labels:
        jenkins.io/credentials-type: secretText
      name: github-webhook-portfolio-ci
      namespace: jenkins
    type: Opaque

